import { useCallback, useEffect, useState } from 'react';
import { getAdminGrievance, listAdminGrievances, updateAdminGrievance } from '../../lib/fiteatsyConsultantsApi';

const states=['','OPEN','IN_REVIEW','IN_PROGRESS','AWAITING_USER','RESOLVED','CLOSED'];

export default function GrievanceManagementModule(){
  const [filters,setFilters]=useState({search:'',status:'',category:'',platform:'',priority:''});
  const [data,setData]=useState({items:[],total:0,limit:25,offset:0});
  const [selected,setSelected]=useState(null);const [events,setEvents]=useState([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async(offset=0)=>{setLoading(true);setError('');try{setData(await listAdminGrievances({...filters,limit:25,offset}));}catch(e){setError(e.message||'Unable to load grievances.');}finally{setLoading(false);}},[filters]);
  useEffect(()=>{void load(0);},[load]);
  const open=async(item)=>{setSelected(item);try{const body=await getAdminGrievance(item.id);setSelected(body.grievance);setEvents(body.events||[]);}catch(e){setError(e.message||'Unable to open grievance.');}};
  const update=async(patch)=>{if(!selected)return;try{const body=await updateAdminGrievance(selected.id,patch);setSelected(body.grievance);setEvents(body.events||[]);void load(data.offset);}catch(e){setError(e.message||'Unable to update grievance.');}};
  return <section className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Support operations</p><h1 className="mt-2 text-3xl font-black text-slate-900">Grievance Management</h1><p className="mt-2 text-sm text-slate-500">Review, assign and resolve reports submitted from the Fiteatsy app.</p></header>
    <div className="grid gap-3 rounded-3xl border border-slate-100 bg-white p-4 shadow-sm md:grid-cols-5"><input aria-label="Search grievances" placeholder="Reference, user or subject" className="rounded-xl border p-3 text-sm md:col-span-2" value={filters.search} onChange={e=>setFilters(v=>({...v,search:e.target.value}))}/><select aria-label="Status" className="rounded-xl border p-3 text-sm" value={filters.status} onChange={e=>setFilters(v=>({...v,status:e.target.value}))}>{states.map(v=><option key={v} value={v}>{v||'All statuses'}</option>)}</select><input aria-label="Category" placeholder="Category" className="rounded-xl border p-3 text-sm" value={filters.category} onChange={e=>setFilters(v=>({...v,category:e.target.value}))}/><button onClick={()=>void load(0)} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Apply filters</button></div>
    {error?<div role="alert" className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</div>:null}
    <div className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="grid grid-cols-[1.2fr_1fr_2fr_1fr_1fr] gap-3 border-b bg-slate-50 px-4 py-3 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Reference</span><span>User</span><span>Subject</span><span>Status</span><span>Created</span></div>{loading?<p className="p-6 text-slate-500">Loading grievances…</p>:data.items.length===0?<p className="p-6 text-slate-500">No grievances match these filters.</p>:data.items.map(item=><button type="button" key={item.id} onClick={()=>void open(item)} className="grid w-full grid-cols-[1.2fr_1fr_2fr_1fr_1fr] gap-3 border-b px-4 py-4 text-left text-sm hover:bg-blue-50"><span className="font-bold text-blue-700">{item.referenceId}</span><span>{item.user?.name||'—'}</span><span className="truncate">{item.subject}</span><span>{item.status.replaceAll('_',' ')}</span><span>{new Date(item.createdAt).toLocaleDateString()}</span></button>)}</div>
    <div className="flex items-center justify-between text-sm text-slate-600"><span>{data.total} total</span><div className="flex gap-2"><button disabled={!data.offset} onClick={()=>void load(Math.max(0,data.offset-data.limit))} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Previous</button><button disabled={data.offset+data.limit>=data.total} onClick={()=>void load(data.offset+data.limit)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Next</button></div></div>
    {selected?<div role="dialog" aria-modal="true" className="fixed inset-0 z-[200] flex justify-end bg-slate-950/40"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={()=>setSelected(null)} className="float-right rounded-lg border px-3 py-2">Close</button><p className="text-sm font-bold text-blue-600">{selected.referenceId}</p><h2 className="mt-2 text-2xl font-black">{selected.subject}</h2><p className="mt-2 whitespace-pre-wrap text-slate-700">{selected.description}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-400">Category</dt><dd>{selected.category}</dd></div><div><dt className="text-slate-400">Platform</dt><dd>{selected.platform}</dd></div><div><dt className="text-slate-400">Network</dt><dd>{selected.networkType||'Not reported'}</dd></div><div><dt className="text-slate-400">App/build</dt><dd>{[selected.appVersion,selected.buildNumber].filter(Boolean).join(' · ')||'Not reported'}</dd></div></dl><div className="mt-6 flex flex-wrap gap-2">{states.filter(Boolean).map(status=><button key={status} onClick={()=>void update({status})} className={`rounded-full border px-3 py-2 text-xs font-bold ${selected.status===status?'bg-blue-600 text-white':''}`}>{status.replaceAll('_',' ')}</button>)}</div><label className="mt-5 block text-sm font-bold">Add internal note<textarea id="grievance-note" className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><button onClick={()=>{const note=document.getElementById('grievance-note')?.value?.trim();if(note)void update({note});}} className="mt-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Save note</button><h3 className="mt-7 font-black">Audit timeline</h3><div className="mt-3 space-y-2">{events.map(event=><div key={event.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{event.action.replaceAll('_',' ')}</b><span className="ml-2 text-slate-500">{new Date(event.created_at).toLocaleString()}</span>{event.note?<p className="mt-1">{event.note}</p>:null}</div>)}</div></div></div>:null}
  </section>;
}
