"""Add ToolUsage table

Revision ID: 3a0b0ac6995c
Revises: 5f5d5cb51fc2
Create Date: 2026-05-09 12:50:29.783233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0b0ac6995c'
down_revision: Union[str, None] = '5f5d5cb51fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('sub_type', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_usages_completed_at'), 'tool_usages', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tool_usages_tool_id'), 'tool_usages', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_usages_user_id'), 'tool_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_usages_user_id'), table_name='tool_usages')
    op.drop_index(op.f('ix_tool_usages_tool_id'), table_name='tool_usages')
    op.drop_index(op.f('ix_tool_usages_completed_at'), table_name='tool_usages')
    op.drop_table('tool_usages')
    # ### end Alembic commands ###
