"""Add UI fields to SessionRequest

Revision ID: 5f5d5cb51fc2
Revises: 53600889d4e4
Create Date: 2026-05-09 11:53:20.596495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5d5cb51fc2'
down_revision: Union[str, None] = '53600889d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_requests', sa.Column('specialist_name', sa.String(length=255), nullable=True))
    op.add_column('session_requests', sa.Column('specialist_role', sa.String(length=100), nullable=True))
    op.add_column('session_requests', sa.Column('specialist_avatar', sa.Text(), nullable=True))
    op.add_column('session_requests', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('session_requests', sa.Column('meeting_link', sa.Text(), nullable=True))
    op.drop_constraint('uq_teams_join_code', 'teams', type_='unique')
    op.drop_index('ix_teams_join_code', table_name='teams')
    op.create_index(op.f('ix_teams_join_code'), 'teams', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_join_code'), table_name='teams')
    op.create_index('ix_teams_join_code', 'teams', ['join_code'], unique=False)
    op.create_unique_constraint('uq_teams_join_code', 'teams', ['join_code'])
    op.drop_column('session_requests', 'meeting_link')
    op.drop_column('session_requests', 'thumbnail_url')
    op.drop_column('session_requests', 'specialist_avatar')
    op.drop_column('session_requests', 'specialist_role')
    op.drop_column('session_requests', 'specialist_name')
    # ### end Alembic commands ###
