"""Add target macros and calculated body fat

Revision ID: dddea0ba61fa
Revises: 0002
Create Date: 2026-05-08 15:30:09.782879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddea0ba61fa'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_baseline', sa.Column('target_protein', sa.Integer(), nullable=True))
    op.add_column('nutrition_baseline', sa.Column('target_fat', sa.Integer(), nullable=True))
    op.add_column('nutrition_baseline', sa.Column('target_carbs', sa.Integer(), nullable=True))
    op.add_column('nutrition_baseline', sa.Column('target_calories', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('calculated_body_fat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'calculated_body_fat')
    op.drop_column('nutrition_baseline', 'target_calories')
    op.drop_column('nutrition_baseline', 'target_carbs')
    op.drop_column('nutrition_baseline', 'target_fat')
    op.drop_column('nutrition_baseline', 'target_protein')
    # ### end Alembic commands ###
