import { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/router';
import ExternalClientHealthIntake from '../../components/external/ExternalClientHealthIntake';
import { getExternalClientIntakeProfile, openExternalClientIntake } from '../../lib/fiteatsyConsultantsApi';

export default function ExternalClientIntakePage(){
  const router=useRouter();const [state,setState]=useState({loading:true,entry:null,profile:null,error:null});const [started,setStarted]=useState(false);const [completedPractice,setCompletedPractice]=useState('');const token=String(router.query.token||'');
  useEffect(()=>{if(!router.isReady)return;openExternalClientIntake(token).then(entry=>{setState({loading:false,entry,profile:null,error:null});if(entry.state==='COMPLETED')setCompletedPractice(entry.practiceName);}).catch(error=>setState({loading:false,entry:null,profile:null,error:error?.data?.error||'INVITATION_INVALID'}));},[router.isReady,token]);
  const start=async()=>{setState(v=>({...v,loading:true}));try{const profile=await getExternalClientIntakeProfile(token);setState(v=>({...v,loading:false,profile}));setStarted(true);}catch(error){setState(v=>({...v,loading:false,error:error?.data?.error||'INVITATION_INVALID'}));}};
  if(completedPractice)return<Completion practiceName={completedPractice}/>;
  if(started&&state.profile)return<ExternalClientHealthIntake token={token} initial={state.profile.intake} practiceName={state.profile.practiceName} onComplete={setCompletedPractice}/>;
  if(state.loading)return<Page><p className="text-sm text-slate-600">Validating your secure invitation…</p></Page>;
  if(state.error)return<Page><h1 className="text-2xl font-semibold">Invitation unavailable</h1><p className="mt-3 text-sm leading-6 text-slate-600">{state.error==='INVITATION_EXPIRED'?'This invitation has expired. Please contact your practitioner for a new link.':state.error==='INVITATION_REVOKED'?'This invitation is no longer active. Please contact your practitioner.':'This secure invitation is invalid or unavailable.'}</p></Page>;
  return<Page practiceName={state.entry?.practiceName}><p className="text-sm font-medium text-slate-500">Welcome, {state.entry?.clientName}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Complete your health profile</h1><p className="mt-4 text-sm leading-6 text-slate-600">Share your health background securely with your practitioner. You can save your progress and return while this invitation remains active.</p><button onClick={start} className="mt-7 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Start Health Profile</button></Page>;
}
function Completion({practiceName}){return<Page practiceName={practiceName}><div className="grid h-12 w-12 place-items-center rounded-full bg-emerald-100 text-xl text-emerald-700">✓</div><h1 className="mt-5 text-2xl font-semibold">Health profile submitted successfully</h1><p className="mt-3 text-sm leading-6 text-slate-600">Your information has been shared securely with {practiceName}. Your Consultant can now review it before your consultation.</p></Page>}
function Page({practiceName,children}){return <main className="grid min-h-screen place-items-center bg-[#f6f7f8] px-5 py-12"><section className="w-full max-w-lg rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-950 text-white"><ShieldCheck size={22}/></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Secure client intake</p><p className="font-semibold text-slate-950">{practiceName||'Your practitioner'}</p></div></div>{children}<p className="mt-10 border-t border-slate-100 pt-5 text-xs leading-5 text-slate-400">This private invitation is scoped to your practitioner and expires automatically.</p></section></main>}
